kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:

  - name: build
    image: gradle:6.6.1-jdk14
    pull: true
    commands:
      - ./gradlew clean
      - ./gradlew test
    when:
      status:
        - success

trigger:
  event:
    - push
