kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
#  - name: build
#    image: gradle:6.6.1-jdk14
#    pull: true
#    environment:
#      GRADLE_USER_HOME: tmp/cache
#    commands:
#      - ./gradlew clean
#      - ./gradlew kotlinDemo:build -x test
#    when:
#      event: [push]
#      status:
#        - success

#  - name: 배포
#    image: drone-example:${DRONE_COMMIT_SHA}
#
  - name: 슬랙 알림
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: 드론테스트용
      template: >
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Deploy* (type: `{{ build.event }}`)
        Repo: <https://github.com/{{ repo.owner }}/{{ repo.name }}|{{ repo.name }}>
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Tags: <https://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.tag }}|{{ build.tag }}>
        Branch: {{ build.branch }}
        Author: {{ build.author }}
        Link:  <{{ build.link }}|Visit build page ↗>
    when:
      status: [ success, failure ]
#    commands:
#      - echo hello
trigger:
  event:
    - push
